server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false # Because Eureka itself should not register itself.
    fetch-registry: false # It doesn't need to discover others.